# This script connects to an Azure-AD Tenet-Controlled Office365 Instance
# And Creates A Local Spreadsheet Of Each Group And All The Membership
#
# Generated by: Marty Nickison, MCSE
#
# Generated on: 01/28/2020

Connect-MSOLService

Install-Module -Name AzureAD -Force

install-module AzureADPreview -Force
install-module MSOnline -Force

Get-MsolGroup | select objectid |
  ForEach-Object {Get-MsolGroupMember -GroupObjectId $_.ObjectID;
  Get-MsolGroup -ObjectID $_.ObjectID | select DisplayName, EmailAddress
  } | export-csv "C:\Office365_Groups_And_Memebers.csv"
